### ISSUE TITLE
universal rendering: hydration does not happen

### ISSUE THREAD

**Issue by wizzard0** [flareact/flareact#115]
### Describe the problem:

Flareact claims to support universal rendering (both ESR and CSR).
However, code does not seem to ever run on the client after rehydration, and it does not seem possible to detect when you're running client-side.

### Link to a minimal reproduction:

```jsx
import React from 'react'

export default function Index() {
 useEffect(()=>{ console.log('client effect') })
 return (
    <h1>
      should print something to console upon page load
    </h1>
  );
}
```

**Comment by traffisco** [comment]
You sure you not missing the import for useEffect in your example?

Import the flareact router in the js file or the _app.js

**Comment by wizzard0** [comment]
@traffisco copied the page component from the larger file and forgot to copy the useEffect imports)

is router required for CSR? the same code prints to console in nextjs without the router, not sure where to read about it

**Comment by traffisco** [comment]
> is router required for CSR? the same code prints to console in nextjs without the router, not sure where to read about it
Its a bug.

**Comment by jplhomer** [comment]
`useEffect` does indeed run on the client for every page component, and it does not run on the edge/server.

See https://github.com/flareact/flareact-site/blob/main/pages/docs/%5Bslug%5D.js on our docs site for an example of this working.

I can't troubleshoot anything else related to your specific issue because you haven't provided a link to a reproduction. Feel free to share a link to a repo if you have additional questions, or ask in Discussions.

**Comment by traffisco** [comment]
@jplhomer its a real bug though, useEffect won't fire unless flareact router is imported in the file(or his parent).

**Comment by jplhomer** [comment]
![Screen Shot 2021-02-06 at 11 23 58 AM](https://user-images.githubusercontent.com/848147/107125154-d0477500-686d-11eb-80d2-f80776a16c30.png)

![Screen Shot 2021-02-06 at 11 23 48 AM](https://user-images.githubusercontent.com/848147/107125160-d5a4bf80-686d-11eb-9550-cb896d52bf00.png)

**Comment by traffisco** [comment]
@jplhomer 
Well, that's strange. 
Just tested on a fresh project and its working as expected. Tested with different flareact and react versions too....
I had the same problem @wizzard0 had when useEffect wasn't firing unless router is imported. Took me a while to find why some pages didn't work.  Don't know what to make of this.

**Comment by wizzard0** [comment]
ok, I still can't make a definitive repro, but for anybody running into the same:
- remove KV workspaces and workers
- remove _flareact directory
- run `npm run deploy` then `npm run dev`
- then it magically starts working.

Might be a bug in Wrangler not flareact.

And with dev server, the first thing to look for is '`500 can't find pagename.js in your content namespace`' in the browser console instead of '`[WDS] Live Reloading enabled`'.

**Comment by webbertakken** [comment]
Looks like errors are swallowed, and hydration stops in some cases.

I also saw `useEffect` being run on the worker instead of in the browser before that.

Unfortunately I was also not able to reliably reproduce this.
