### ISSUE TITLE
Public environment variables not found or undefined.

### ISSUE THREAD

**Issue by jonhainstock** [flareact/flareact#173]
### Describe the problem:

The [firebase example shows use of public environment variables](https://github.com/flareact/flareact/blob/canary/examples/with-firebase/.env.local) sourced from the `.env` files. 

I've tried using the example and I'm unable to access the environment variables. 

I also tried using wrangler environment variables. When refreshing the page, I see the variable for a second and then I see an undefined message. 

<img width="2672" alt="Screen Shot 2021-07-09 at 9 33 54 AM" src="https://user-images.githubusercontent.com/1247220/125096221-8c65cf80-e09a-11eb-9493-c6da0f053f39.png">

I suspect the wrangler environment variables are only accessible to the server. 

### Link to a minimal reproduction:

[Here is a link to the repo](https://github.com/jonhainstock/flareact-env). Set `account_id` in the wrangler file and run `yarn && yarn dev` to replicate. 

[You can see how the environment variables are being called here](https://github.com/jonhainstock/flareact-env/blob/master/pages/index.js).

**Comment by jonhainstock** [comment]
I was able to use [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack) and a custom webpack config in `flareact.config.js` to set environment variables. 

Here is what my config looks like for anyone else who is looking to solve this.

```
const Dotenv = require('dotenv-webpack');

module.exports = {
  webpack: (config, { dev, isWorker, defaultLoaders, webpack }) => {
    config.plugins.push(new Dotenv({path: `./.env.${dev ? 'development' : 'production'}`}));
    return config;
  },
}
```

**Comment by tj-kev** [comment]
Thanks! Glad you many to solve it.
