### ISSUE TITLE
Access dev server from local network

### ISSUE THREAD

**Issue by erenakbulut-q** [flareact/flareact#175]
### Describe the problem:

Is it possible to specify ip when start development server like `wrangler dev --ip 172.20.10.2   ` for access website from another device in my network?

### Link to a minimal reproduction:

Using the example and template

**Comment by tj-kev** [comment]
Sorry, this is not supported at the moment. Would be a good to support though along with custom ports.

**Comment by joelnet** [comment]
I have been using `ngrok` for this which also makes the address public.

```
ngrok http --host-header=rewrite 8080
```

**Comment by tj-kev** [comment]
Closing this issue as miniflare (which is now maintained by Cloudflare) or ngrok seem to be the way to go.
