### ISSUE TITLE
Data fetching w/getEdgeProps from app api?

### ISSUE THREAD

**Issue by MaxOrelus** [flareact/flareact#179]
I'm trying to figure out how I can fetch data from the api (`/api` folder in the pages) using `getEdgeProps`.

```js
// index.js

export async getEdgeProps() {
  const data = await fetch("/api/health")
  // const data = await fetch("http://localhost:8080/api/health") -- full path
  return {
    props: {
      ...data
    }
  }
}

function Home(props) {
  console.log(props)

  return <div>hello world</div>
} 
```

In this example it doesn't work because fetch expects the full URL instead of the relative path. Next.js allows this type of behavior, but that's fine I also tried the full url path while in `flareact dev`. When I put the full url path `http://localhost:8080/api/health` I get a 403 Forbidden error from the request.

Could someone provide an example of them calling an endpoint on the api within `getEdgeProps` which works? The examples in the Flareact documentation shows an invocation of a method which is not catalogued in example code.

**Comment by tj-kev** [comment]
I believe this may be down to getEdgeProps running on the Cloudflare side which will have no concept of localhost.

You could try a tool such as [ngrok](https://ngrok.com/) to create a publicly available endpoint to your localhost?

Unless you have a specific use case I would not recommend calling the apis from getEdgeProps. Anything you could do from the api could be done just as easily from getEdgeProps itself.
