### ISSUE TITLE
Nothing works - button onClick doesn't work, router.push doesn't work

### ISSUE THREAD

**Issue by adembacajglobant** [flareact/flareact#191]
### Describe the problem:

Hello everyone, I just started moving an existing project from React.js to Flareact. I have created a new project with Flareact, and just started playing with different stuff. 

<button onClick={navigate}>...</button>
this onClick event is not calling navigate function.

router.push('/home') - this is not working, it throws an error: ReferenceError: window is not defined

And also a question for you who are using it: 
1. Do we have componentDidMount, componentDidUpdate or any other solution?

**Comment by tj-kev** [comment]
For the onclick issue, do you have a code example? Are you getting the "window is not defined" error in the browser console?

For "componentDidMount" etc I've not tried it personally but can't think of a reason why it wouldn't work.

**Comment by tj-kev** [comment]
I'm going to assume this issue was resolved.

Can reopen if you have further problems.
