### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by appsdevpk** [flareact/flareact#195]
### Describe the problem:
Its the new installation of flareact, i created a sample project using the template, then installed the dependencies and when try to run wrangler dev, it give below error.

![image](https://user-images.githubusercontent.com/516860/142048469-5dd64087-8c0a-4ee2-9ba6-1571c87a6f6c.png)

**Comment by traffisco** [comment]
Windows is not supported. Run from WSL
