### ISSUE TITLE
Trouble loading frameworks - material ui 

### ISSUE THREAD

**Issue by shaunm** [flareact/flareact#206]
Hi, 

I am coming from a pure react background and was getting starting with Flareact, but ran into a problem just setting up a boilerplate example.

My index.js:

```import * as React from 'react';
import Button from '@mui/material/Button';

export default function Index() {
  return (
    <div>
      <h1> Hello, world!</h1>
      <Button>Click Me</Button>
    </div>
  );
}
```

Logs:
```
[worker] TypeError: Cannot read properties of null (reading 'registered')
[worker]     at worker.js:38:22760
[worker]     at Object.render (worker.js:1:1770)
[worker]     at e.t.render (worker.js:22:15365)
[worker]     at e.t.read (worker.js:22:14272)
[worker]     at Object.t.renderToString (worker.js:22:19420)
[worker]     at Object.b [as renderPage] (worker.js:6:41968)
[worker]     at worker.js:1:4189
[worker]     at l (worker.js:6:43920)
[worker]     at Generator._invoke (worker.js:6:43673)
[worker]     at Generator.next (worker.js:6:44283)
```

Perhaps this isn't within the scope of this issues section, but I was wondering if anyone knew how to run in "debug" mode to at least examine non compiled worker code or if anyone had any suggestions? 

Weirdly enough, I was able to get it work briefly for a few moments locally, but as soon as I push it to the worker server it breaks.

Thanks,
Shaun

**Comment by traffisco** [comment]
I would start with https://github.com/flareact/flareact/tree/canary/examples/with-styled-components example and material ui on  Next js as a reference

**Comment by shaunm** [comment]
> I would start with https://github.com/flareact/flareact/tree/canary/examples/with-styled-components example and material ui on Next js as a reference https://github.com/mui-org/material-ui/tree/master/examples/nextjs

This was helpful, it turns out switching to yarn fixed a lot of problems. Do you know if its possible to enable react development mode?

**Comment by traffisco** [comment]
@shaunm if you got it working, a pr to an example would be great

**Comment by shaunm** [comment]
@traffisco I will issue a pull request in a bit, I am facing one last problem which I just posted a discussion about.

**Comment by sebinievas** [comment]
Will you link to the PR so we can see what was the problem? Same error but different framework here.

**Comment by shaunm** [comment]
> Will you link to the PR so we can see what was the problem? Same error but different framework here.

https://github.com/flareact/flareact/pull/208#issue-1098726437

This was a while back, so the code is probably stale. I think it ended up being a problem with wrangler version and node.
