### ISSUE TITLE
Dynamic sitemap

### ISSUE THREAD

**Issue by melloradamj** [flareact/flareact#21]
How would you create a dynamic sitemap for a site built on this?

**Comment by jplhomer** [comment]
I'd recommend tapping into the [custom Webpack config](https://flareact.com/docs/custom-webpack-config) to run a script which generates your sitemap. The script can deposit any file into your [`/public` folder](https://flareact.com/docs/static-file-serving):

```js
module.exports = {
  webpack: (config, { dev, isWorker }) => {
    // only when performing a production deploy for the worker:
    if (!dev && isWorker) {
      myCustomGenerateSitemapScript();
    }
    return config;
  },
};
```

Feel free to PR an example to this repository if it works for you.

**Comment by subhendukundu** [comment]
On the same context, I am moving my existing workers page to flareact. The existing approach where I was creating a `sitemap.xml` with api route.
```
const getSitemap = pages => `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	${pages
		.reduce((acc, page) => {
			return acc + `
				<url>
					<loc>${`https://example.com/${page.name}`}</loc>
				</url>
			`
		}, '')}
</urlset>
`

const sitemap = async () => {
	const files = await PAGES.list({ limit: 200 })
	const sitemaps = getSitemap(files.keys)
	console.log(sitemaps)
	return response.xml(sitemaps)
}

export default sitemap 

```
Do you think we could do something like this with flareact? Sitemap on the fly?

**Comment by subhendukundu** [comment]
One possible soultion would be 
```
export async function getEdgeProps() {
   // return a response before it goes to any other functions?
   return new Response() // only if I have access to Response, ideally it should.
}
```

**Comment by traffisco** [comment]
> Do you think we could do something like this with flareact? Sitemap on the fly?

Flareact has no way knowing about the real structure of your project. Especially when dynamic pages and routes involved. 

If you manage your url slugs from db or kv storage, you can generate them on the fly with custom implementation with api routes or generating sitemap in advance like @jplhomer suggested.

**Comment by subhendukundu** [comment]
Yes, thats what I am doing in the example if you see the above comment.
`const files = await PAGES.list({ limit: 200 })`
It's getting the list of 200 pages and creating a sitemap.xml. It's a cheeky way of doing this. https://github.com/subhendukundu/cool-bio-worker/blob/main/src/pages/_sitemap.js#L22
I could just put it in `api/_sitemap.xml` then resolve it in Cloudflare redirect rules. Before that I wanted to know I could be the best way to do this.

**Comment by traffisco** [comment]
The proper way is to put your code in the api folder to bypass all the react rendering stuff `api/sitemap.js`

**Comment by subhendukundu** [comment]
Umm thats exactly what I am struggling with ATM 😔 (https://github.com/flareact/flareact/issues/42#issuecomment-778752018)
It will take me a while to get a hang of Flareact. Could you help me with an example of this? Especially how to `Response.redirect(url)` in Flareact.

**Comment by traffisco** [comment]
You mixing up different topics/scenarios .
For generating custom responses(dynamic sitemap is a good example), use Api routes:
https://flareact.com/docs/api-routes

Server side(worker) redirect from `getEdgeProps` it currently not supported(open a feature request).  
You can return from `getEdgeProps` a redirect parameter and do a client side redirect using flareact router.

**Comment by subhendukundu** [comment]
Thank you. I have created a PR for redirect from `getEdgeProps`. #124
