### ISSUE TITLE
Error Running Init Command 

### ISSUE THREAD

**Issue by brandonculver** [flareact/flareact#22]
```wrangler generate my-project-1 https://github.com/flareact/flareact-template```

Creating project called `my-project-1`...
Error:  Error replacing placeholders `/home/brandonculver/Code/my-project-1/.github/workflows/deploy.yml`
Info: caused by liquid: Unknown variable
  with:
    requested variable=secrets
    available variables=authors, crate_name, project-name

Error: tried running command:
/home/brandonculver/.cache/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/flareact/flareact-template --name my-project-1 --force
exited with exit code: 1

I tried deleting .cache/.wrangler cache and starting over, but I got the same error.

**Comment by jplhomer** [comment]
Thanks for flagging this, @brandonculver! It was a conflict with a `deploy.yml` secret syntax + Cargo's liquid syntax. I've pushed up a fix and this should be working again 🎉
