### ISSUE TITLE
with-typescript example does not work

### ISSUE THREAD

**Issue by anonrig** [flareact/flareact#238]
```bash
➜  with-typescript git:(canary) ✗ wrangler --version
wrangler 1.19.12
```

<img width="1624" alt="Screen Shot 2022-07-01 at 12 33 51 PM" src="https://user-images.githubusercontent.com/1935246/176934991-1062b8f5-ed7b-41c8-a9b4-cd0d534c54e3.png">

**Comment by traffisco** [comment]
You running windows? Not sure it's supported.
Try running from wsl

**Comment by anonrig** [comment]
I'm running from macOS

**Comment by traffisco** [comment]
Node version?

**Comment by anonrig** [comment]
```
➜  bookclub git:(main) ✗ node -v
v18.4.0
```

**Comment by tj-kev** [comment]
Does the public folder exist? If not can you make one and try again?

**Comment by anonrig** [comment]
Now I'm receiving a different error due to Wrangler 2

<img width="1613" alt="Screen Shot 2022-07-03 at 1 47 49 PM" src="https://user-images.githubusercontent.com/1935246/177051392-a7e455fd-79c5-423a-be53-380fff1b2e18.png">

**Comment by tj-kev** [comment]
Flareact is not currently compatible with wrangler v2. This is due to it needing some modifications to the build scripts. It will be supported in a future update.

In the mean time I recommend using the latest version of wrangler v1.

**Comment by anonrig** [comment]
I downgraded to version 1.19.12. The issue persists:

<img width="1616" alt="Screen Shot 2022-07-03 at 1 53 34 PM" src="https://user-images.githubusercontent.com/1935246/177051575-79e9de3c-e8c6-44a8-9394-0d6a792cc3e8.png">

**Comment by tj-kev** [comment]
Just tried this myself with the same error. Can you add an "out" folder as well? See if that works for you?

**Comment by anonrig** [comment]
`out` folder works, thanks. I believe the developer experience should be much smoother, but it seems there are more significant tasks `flareact` needs to resolve (like wrangler 2 support), and I'll be happy to help.

**Comment by tj-kev** [comment]
Yeah I agree. Any help is always appreciated!

**Comment by anonrig** [comment]
Is there a slack/discord channel to communicate for flareact?

**Comment by traffisco** [comment]
> `I believe the developer experience should be much smoother.`
Looks like it's only an issue when cloning the examples, using the base template should work as expected.

**Comment by tj-kev** [comment]
> Is there a slack/discord channel to communicate for flareact?

Not at the moment. But I can certainly set one up if there is enough interest.

I'm going to close this issue now as the original problem has been resolved.
