### ISSUE TITLE
Shallow Links/Routing

### ISSUE THREAD

**Issue by tj-kev** [flareact/flareact#246]
### Describe the problem:

Currently shallow routing is not supported. Used if you want to perform URL updates but not reload the getEdgeProps from the worker.

NextJS Implementation can be seen [here](https://nextjs.org/docs/routing/shallow-routing).

To keep it consistent with NextJS, I think we should follow their implementation of adding this to a ```options``` object on the router. Currently the router ```scroll``` option is at the top level, not the ```options``` object. This should be moved. However, this would be a breaking change and maybe only available in the V2 release.

```javascript
router.push("/?counter=10", undefined, { shallow: true })
```

Links should also support this functionality.
```jsx
<Link href="/?counter=10" shallow={ true }>
      <a>My First Post</a>
</Link>
```

**Comment by kkeene1** [comment]
Implemented in #250 

As the scroll option on router.push is undocumented I've changed it to a top level options object containing scroll and shallow params instead.
