### ISSUE TITLE
Issue with nested/dynamic routes

### ISSUE THREAD

**Issue by maxkostinevich** [flareact/flareact#32]
I'm trying to migrate a blog from Next.js to Flareact, and have a weird issue with routes:

I have Posts under `/pages/posts/[slug].js` and this works fine, however I couldn't figure out how to make a `/posts/` page with the list of all posts. I've tried to put `index.js` to `/pages/posts/index.js`, but it seems like that page is never loading (unless I put `/posts/index` in my browser). I also tried to create `posts.js` page in `/pages/posts.js` - however in this case my dynamic routes stop working. 

Do I miss something? Thank you in advance.

**Comment by jplhomer** [comment]
Hi @maxkostinevich - I think this is indeed a bug. Need to update the routing logic to ensure a dynamic route can co-exist with an `/index.js` etc page as you described.

I'll add this to the list and hopefully get to it soon!
