### ISSUE TITLE
Moving existing website to flareact

### ISSUE THREAD

**Issue by dev-launchers-sandbox** [flareact/flareact#33]
I really love what y'all are building! I've spent some time trying to move my website to use flareact for SSR, but I'm stuck with this error when I ran flareact dev:
`
👀  ./src/components/modules/MentorshipTiers/PhotoHolder/PhotoHolder.module.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
 @ ./src/components/modules/MentorshipTiers/PhotoHolder/PhotoHolder.js 2:0-45 5:15-20
 @ ./src/components/modules/MentorshipTiers/PhotoHolder/index.js
 @ ./src/components/modules/MentorshipTiers/MentorshipTiers.js
 @ ./src/pages/members.js
 @ ./src/pages sync \.js$
 @ ./index.js
`
Am I getting this error because I'm using CSS Modules? I saw the documentation said it's not supported yet. Is it on the roadmap?
This is our source code https://github.com/dev-launchers/platform__website/tree/compare-flareact-site.

**Comment by jplhomer** [comment]
Thanks for the report! I'm not 100% sure what character the CSS loader is tripping up on - but you're correct in that CSS Modules are not supported yet. 

I hope to get to it in the future 👍

**Comment by dev-launchers-sandbox** [comment]
Thanks, any idea how to workaround the CSS Modules issue? Also it would be nice if the CSS Module warning is on the main page.

**Comment by jplhomer** [comment]
I'd recommend using a [custom Webpack config](https://flareact.com/docs/custom-webpack-config) as described here to support CSS Modules for the time-being.

**Comment by SparklingFun** [comment]
I met similar error when I was trying import 'semantic-ui-css', I solved by using `file-loader` and `url-loader` in custom webpack config for some `.svg|.woff` files, maybe you can have a try.

**Comment by SparklingFun** [comment]
I tried my solution on my lunch break, your errors were gone (on your `compare-flareact-site` branch, with a simple config). I stopped at preview so the rest part I can't help now.
Here is my `flareact.config.js`
```javascript
module.exports = {
    webpack: (config, { dev, isWorker, defaultLoaders, webpack }) => {
        const fileLoader = {
            test: /\.(jpg|jpeg|png|woff|woff2|eot|ttf|svg)$/,
            loader: 'url-loader',
            options: {
                limit: 10000,
            }
        }
        config.module.rules.push(fileLoader);
        config.watchOptions = { ignored: /node_modules/ }
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: 'empty'
        }
        return config
    }
}
```

PS: There is an incorrect path in [this CSS](https://github.com/dev-launchers/platform__website/blob/40f21e96ef48b3dcd9bb87fd98eb49e6e1913460/src/components/modules/MentorshipTiers/SignUpForm/SignUpForm.module.css#L5), maybe you need a fix. :joy:

**Comment by jplhomer** [comment]
CSS modules is now supported! https://flareact.com/docs/built-in-css-support#css-modules
