### ISSUE TITLE
API Routes not working

### ISSUE THREAD

**Issue by cj** [flareact/flareact#41]
flareact: 0.7.1

I followed the example here https://github.com/flareact/flareact/blob/canary/docs/api-routes.md and this is the response:

![CleanShot 2020-10-30 at 17 45 03](https://user-images.githubusercontent.com/1819/97762879-dfcd5a00-1ad7-11eb-8c6a-810225c2b4ad.png)

I have tried deleting the node_modules, clearing cache etc... but to no avail.

Let me know if you need any more details!

**Comment by jplhomer** [comment]
Hi @cj I can't reproduce this - in a fresh install w/the latest version of Flareact, API routes work fine.

I noticed you have Typescript files in your project - perhaps this is related to a modification of Flareact internals to support Typescript?

**Comment by cj** [comment]
@jplhomer you are indeed correct, it was a change that I had made in the index.js.  It's all working now, thought I was going crazy, even had flashbacks of `;` in IE6 lol.

I'll be posting my Typescript example repo soon.

Thank you again for this lib, have a great weekend!
