### ISSUE TITLE
Pass event object to getEdgeProps() ?

### ISSUE THREAD

**Issue by davidbarratt** [flareact/flareact#42]
I was thinking of a few scenarios where it would be helpful to pass the `event` object to `getEdgeProps()`. Primarily if you want to use [event.waitUntil()](https://developers.cloudflare.com/workers/learning/fetch-event-lifecycle#waituntil).

Alternatively we could have another method like `edgeEffect()` that would be an `async` function who's return would be put into `event.waitUtnil()` for the user.

**Comment by cj** [comment]
@davidbarratt I have a patch right now you can use with patch-package https://gist.github.com/cj/40a150e67213bb90510bfd06771a74ae it adds TS support, critical inline css, `event` passed to `getEdgeProps` and an extra return param for `getEdgeProps` called `response` that allows you to return your own response, like a redirect for protected urls (it also works with the router).

I'll be making it a series of pull request, but feel free to use the patch :)

**Comment by davidbarratt** [comment]
> an extra return param for `getEdgeProps` called `response` that allows you to 

Why not just accept a return of a Response object and do an `instanceof Response` ?

Though this makes me wonder if I could have a page route that has no React compoment at all? If so... you aren't really getting edge "props" anymore. :/

I wonder if it would be better to just let people "hook" into the execution (at the front?). Like it might be nice to take over a `fetch` event rather than having flareact do it's thing. For example, let's say I want a dynamic sitemap at `/sitemap.xml` would I have a "page" that has no react compoment? Or should I just be able to takeover the main `fetch` event? Or maybe we allow additional fetch handlers?

**Comment by cj** [comment]
> > an extra return param for `getEdgeProps` called `response` that allows you to
> 
> Why not just accept a return of a Response object and do an `instanceof Response` ?

It is so you can pass other options like `revalidate`, I have updated the patch and example to reflect that. 

> 
> Though this makes me wonder if I could have a page route that has no React compoment at all? If so... you aren't really getting edge "props" anymore. :/

Well this use case is for protecting a page i.e.:

```typescript
import Link from 'flareact/link'
import { protectedPage } from '~/lib/protected-page'

export const getEdgeProps = protectedPage()

export default function ProtectedPage({ authorized }) {
  return (
    <div className="flex flex-col items-center justify-center flex-grow">
      <div className="flex flex-col items-center prose">
        <h1>Protected Route!</h1>

        <p>Authorized: {authorized ? 'true' : 'false'}</p>

        <Link href="/">
          <a>Home</a>
        </Link>
      </div>
    </div>
  )
}
```
> 
> I wonder if it would be better to just let people "hook" into the execution (at the front?). Like it might be nice to take over a `fetch` event rather than having flareact do it's thing. For example, let's say I want a dynamic sitemap at `/sitemap.xml` would I have a "page" that has no react compoment? Or should I just be able to takeover the main `fetch` event? Or maybe we allow additional fetch handlers?

You can handle that in the index.js and have it not even touch flareact, which is the beauty of it (easy to customize).

**Comment by jplhomer** [comment]
@davidbarratt I like this idea! Should be a simple PR if you're interested 👍 Otherwise I can get to it sometime.

**Comment by davidbarratt** [comment]
@cj instead of accepting a response object, I think it would be better to match Next.js's API a little better and accept a `notFound` or `redirect` property of the return object: https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

**Comment by cj** [comment]
@davidbarratt I like the idea of having a redirect prop for simple usage 👍 

I think it's also nice to expose response for more control.

**Comment by idl3** [comment]
@davidbarratt the event argument was added to getEdgeProps in #83 that should do the trick right?

**Comment by davidbarratt** [comment]
It looks like it (from the code)!

**Comment by subhendukundu** [comment]
I have a use case where I need to redirect a user based on some data in KV.
https://github.com/subhendukundu/cool-bio-worker/blob/main/src/pages/bio/index.js#L28

So can do something like this? If this is already possible please guide me the doc

```
export async function getEdgeProps({ params, event }) {
  const { bio } = params;
  const data = await BIOS.get(bio, "json");
  // redirect them if it has forwardLink link alreadry
  if (data.forwardLink) {
    return   Response.redirect(data.forwardLink)
  }
  return {
    props: {
      data,
    },
  };
}
```
If it was NextJS I could do something like
```
return {
      redirect: {
        permanent: false,
        destination: forwardLink.url,
      },
};
```
