### ISSUE TITLE
SSR only?

### ISSUE THREAD

**Issue by adam-janis** [flareact/flareact#43]
Hey 👋🏻 Currently trying Flareact out and must say that I like it so far! 

However, I do have a use-case where I would prefer to render the site on Edge only - and therefore also not sending the initial-data in the HTML (from getEdgeProps), is there any way I can achieve this right now? 

Many thanks!

**Comment by jplhomer** [comment]
Hey @adam-janis - you can use `revalidate: 0` to tell Flareact to never cache your page response or props: https://flareact.com/docs/data-fetching#caching-and-revalidation

**Comment by adam-janis** [comment]
Thanks for a prompt response! I meant to have SSR only, as even with `revalidate: 0` are the props sent out to the client in the HTML as initial-data - not needed in case everything is rendered (and eventually cached) on server-side already.

Anyways, I actually just solved my use-case by not rendering histograms (the biggest chunk) on the server-side and leaving the client to render it - this way I do not have duplicated data (JSON + rendered) in the response. Making me happy as it saved me response size and precious worker CPU time as well. :)

**Comment by jplhomer** [comment]
Ahh - glad you found a solution!
