### ISSUE TITLE
Dynamic Page Matches Custom App Page (_app.js)  Causing Rendering Failure

### ISSUE THREAD

**Issue by odacrem** [flareact/flareact#70]
The following Dynamic Page configuration will cause rendering errors because the "App" component/page will resolve to [group].js rather than _app.js
```
pages/[group].js
pages/_app.js
pages/posts/[slug].js
```
This occurs because the test for [isDynamic in the resolvePagePath function](https://github.com/flareact/flareact/blob/8e2d90b222f6b916e843785afe7f01d15fbc1785/src/worker/pages.js#L10) will match the page path "_app.js" to the dynamic page  "[group].js"

Thus the App Provider will render the component defined in [group].js as the "App" component rather than the component defined in _app.js.

Steps to reproduce:

Setup the following page structure:
```
pages/[group].js
pages/_app.js
pages/posts/[slug].js
```
Loading up pages will cause the [group].js component to be used as the App component rather than the component defined in _app.js

A quick and dirty fix is to treat getPage(_app.js,...) as a special case and never try to match it against dynamic page definitions.

e.g. ```const isDynamic = pagePath != "/_app" && DYNAMIC_PAGE.test(page)```

**Comment by jplhomer** [comment]
Fixed in https://github.com/flareact/flareact/pull/71
