### ISSUE TITLE
Use getEdgeProps in component files

### ISSUE THREAD

**Issue by traffisco** [flareact/flareact#81]
Please add support to use getEdgeProps in component files.
I know Next.js don't support it, but they don't do all the fancy edge rendering :)
Alternatively,  an api to kv storage may be exposed to store api responses with a revalidation parameter.

Thanks,
Vadim

**Comment by jplhomer** [comment]
Hey Vadim! I don't foresee Flareact supporting `getEdgeProps` in components, as you can already use page components for the same thing.

I like your idea for caching API responses in the KV. You can already do that today if you'd like — or it will become even simpler once we implement data hooks: https://github.com/flareact/flareact/discussions/49

**Comment by davidbarratt** [comment]
This issue could be solved by #92
