### ISSUE TITLE
Passing query parameters fires getEdgeProps twice.

### ISSUE THREAD

**Issue by traffisco** [flareact/flareact#91]
When query parameters are passed to a route, the page rendered twice. 
If the pages has `getEdgeProps`, it also fired twice doubling every API call that might be there.

Thanks,
Vadim

**Comment by jplhomer** [comment]
Hi @traffisco could you please provide more information with an example to code where this can be reproduced? I'm not sure I follow.

**Comment by traffisco** [comment]
```
export async function getEdgeProps({ query }) {

    const delay = (milliseconds) => new Promise(resolve => setTimeout(() => { resolve(Date.now()) }, milliseconds));
    const time = await delay(2000);
    return {
        props: {
            time
        },
        revalidate: 60,
    };
}

export default function test({ time }) {
    return (
        <div>
            {time}
        </div>
    )
}
```

When query parameters are passed `test?q=test` , date changes **again** after 2 seconds. If no parameters, date is set only once.
Looks like it happens only in local dev, appears to work as expected on workers dev or in production

**Comment by jplhomer** [comment]
Ahh, that makes sense:

> **Note**: In development, props are requested each page load, and no caching is performed.

Per https://flareact.com/docs/data-fetching#caching-and-revalidation
