### ISSUE TITLE
userouter causes exception

### ISSUE THREAD

**Issue by calendee** [flareact/flareact#95]
### Describe the problem:

Per the documentation, a route component should be able to use the `useRouter` hook to get information about path.

However, using `const router = useRouter();` consistently results in an exception and the route displays the Cloudflare Error 1101 Ray information. 

### Link to a minimal reproduction:

https://github.com/calendee/flareact-use-router-issue-95

**Comment by jplhomer** [comment]
Hey @calendee! In your example, it looks like you're returning `Response` from your components. These pages expect a React component to be returned instead - see the examples on https://flareact.com/ for more.

I'm guessing there is an error related to this in your console logs (though it is likely cryptic).

**Comment by calendee** [comment]
Thanks so much @jplhomer. That was exactly the issue. I was actually trying to use `useRouter` for an API route and it wasn't working. So, I made that minimal reproduction to show it wasn't working but used it incorrectly 🤦‍♂️.

Any thoughts of making useRouter work similarly for API routes? Not strictly necessary but could make building APIs a bit more flexible.
